### PR TITLE
Layouting etc

### PR DESCRIPTION
**Pull request by Klap-in**
Extensive update, which layouts the pages with help of markdown instead of html. 
Further some layouting is changed a bit. See also below for some examples.

### CODE REVIEW

**Comment by gabsprates** [comment]
@Klap-in Great! Do you need some help?

**Comment by Klap-in** [comment]
Below my approach so far for relayouting typical parts:
- below the 'Parameters' section use definition list:
  ```markdown
  `$variable`
  (here one EMPTY new line, no spaces. This ensures all sections in definition list are grouped)
  : Explanation
    
    Second line Explanation
  ```

- mark all text that user of mPDF types with `` characters, as inline code.
  e.g. 
  ```markdown
  string: `'text'`
  int: `0`  `3`
  array `array(3,5)`
  ```
- use lists to list values below **Values** subheading (and sometime a definition list if it has long explanations of the values)

- make referers to mpdf-variables and function if missing
- add ` markdown="1"` to divs or table cells which contain markdown syntax
- maximum indention for markdown is 2 spaces. (more spaces is shortcut for a code block)
- apply simple indention to html  e.g. tables (too deep indention === code block)
- replace code block syntax (this allows to indent code block inside lists/definistions.  
   `{% highlight php %}    ..code lines..    {% endhighlight %}`-wraps by ` ```php    ..lines..    ``` `-wraps
- replace html by markdown italic `*`, bold `**`, lists , etc
- escape `|` to `\|` to prevent interpretation as table
- replace html entities by original character. normally `&amp;` `&lt;` `&gt;` can be replaced by `&`, `<`, `>`. 
  (Sure when wrapped as inline code `` )
- and more...

If you like to relayout some parts, please notify/ask here for section of interest, for you start relayouting some part, to prevent double work..

**Comment by finwe** [comment]
Do the backticks really work through Github Pages markdown formatter? I faintly remember I was experiencing some problems with them...

**Comment by Klap-in** [comment]
I installed locally Jekyll. There it is working...
How could we test somewhere here if this PR is working on Github Pages as well?

**Comment by finwe** [comment]
I am afraid the local jekyll is not 1:1 with Github pages. I guess only way to test it is by mirroring it on one's own github pages.

**Comment by Klap-in** [comment]
According to https://help.github.com/articles/using-syntax-highlighting-on-github-pages/, my impression is that the backticks are supported.

**Comment by finwe** [comment]
Hmm, it seems ok, I've tested it on my account github pages. Well then. Thanks for the hard work!

**Comment by Klap-in** [comment]
Ok, nice. Thanks for the testing!

**Comment by Klap-in** [comment]
I think all pages are now layouted using appropriate markdown syntax.

I think it is now in a state which is suitable for merging.
Any feedback is welcome!

**Comment by finwe** [comment]
This is awesome! I will test it sometime later today. In the meantime, could you please rebase this on top of development branch instead of merging development into the branch? Thanks!

**Comment by Klap-in** [comment]
Rebase is done!

**Comment by finwe** [comment]
Merged, awesome job! Thanks a lot.

**Pull request closed without merging**
